### ISSUE TITLE
Not working on Flatpak 1.6.5 / Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by rbi** [flathub/org.eclipse.Java#33]
*how to reproduce*
* Try to update the Eclipse flatpak with Flatpak 1.6.5 on Ubuntu 20.04.

*what happened*
* An error message is shown `Error: org.eclipse.Java needs a later flatpak version`.
* Eclipse is not updated

*what should happen*
* No error message
* Eclipse is updated

I use Flatpak so that I don't need to upgrade my whole operating system just to have the newest versions of some software. Not supporting this not-to-old Flatpak version which is used in a very common Linux distribution breaks one of the key benefits of Flatpak.

**Comment by akurtakov** [comment]
See https://github.com/flathub/org.eclipse.Java/commit/a39270453dbdd561648c564eea9131f094f3691b for details.

**Comment by rbi** [comment]
I don't remember issues with something not able escape the sandbox. Maybe not everybody is affected? Do you really need to raise the minimum Flatpak version to fix the other problem? Wouldn't it be enough to just have Flatpak 1.7.1 installed instead of requiring it for everybody?

**Comment by rbi** [comment]
What exactly was the problem with using hosts Java versions? Is there a bug report describing it? is there really no other way of fixing it? I don't remember any problems using my host Java. Java are just files too after all and accessing files on the host file system did work in earlier Flatpak versions too.

I guess you can have different definitions of "seamless experience". I use Flatpak to have up-to-date software versions without fiddling around with PPAs. Using the official Eclipse installer instead of setting up PPAs just because of one broken flatpacked App for me is more convenient.

**Comment by mbooth101** [comment]
The problem was that it was users were unable to add Java 1.8 or earlier JDKs to their IDE on certain versions of flatpak before the document portal was able to properly export directories into the sandbox.

I have been treating RHEL as our support baseline and even RHEL 8, which I think was released in 2019, now has flatpak >= 1.8.5. IMO Ubuntu does a great disservice to its users by shipping older software in their newer releases. I assume this is why in the official Flathub setup guide, which I linked above, instructs users to install flatpak from a PPA. Although I'm no Ubuntu expert, this PPA looks like it contains packages for your distribution (20.04/Focal).

TBH I'm not really interested in supporting configurations that are not recommended by Flathub, I don't know if @akurtakov feels differently.
