### ISSUE TITLE
[RPM] rpmdevtools not found

### ISSUE THREAD

**Issue by mcoufal** [flathub/org.eclipse.Java#38]
After installing RPM plugin, some wizards aso. work with executables in rpmdevtools package, but flatpak can't find these (they're on host system). However, I'm not sure whether there is a plan to support such tools.

How To Reproduce:
1. have rpmdevtools package installed
2. have RPM plugin installed (RPM 7.1.0 in Marketplace)
3. run Eclipse
4. create new RPM project
5. try to create new 'Specfile based on a template' (under 'New' > 'Other...' > 'RPM')

The wizard with an error appears, as can be seen in the attached screenshot:
![rpmdevtools_not_found](https://user-images.githubusercontent.com/26609411/120784920-e4099c00-c52c-11eb-93a9-acf20e8f5caa.png)

My Configuration:
Eclipse SDK
Version: 2021-06 (4.20)
Build id: I20210603-0040
Java runtime version: 15.0.2+7-27
Java version: 15.0.2

**Comment by Mek101** [comment]
Where are those tools installed? If they're anywhere in `/usr`, this is to be expected, as flatpak prevents any application from reading it

**Comment by mcoufal** [comment]
They are under /usr/bin/...

**Comment by vrubezhny** [comment]
Host's `/usr/bin` is mapped to `/var/run/host/usr/bin` in Sandbox. In theory we can add it to `$PATH` in order to make the tools executables available from under the Sandbox. 
But some programs read/require to have some config files to be available from `/etc/` or some other directories, some of them are mapped as well, for example `/etc` -> `/var/run/host/etc` - but in fact they cannot be accessed by the executables this way. 

@mcoufal  Could you please test a  flatpak build that has $PATH variable set to `PATH=/app/bin:/usr/bin:/var/run/host/usr/bin` - it can be can be installed with the following command:

```
flatpak install --user https://dl.flathub.org/build-repo/53718/org.eclipse.Java.flatpakref
```

**Comment by mcoufal** [comment]
Hi @vrubezhny,
I just tested the build you mentioned, I double checked the `PATH` inside the sandbox:
```
[mcoufal@host ~]$ flatpak run --command=sh org.eclipse.Java
[org.eclipse.Java ~]$ echo $PATH
/app/bin:/usr/bin:/var/run/host/usr/bin
```

and it's the same as you wrote. When listing `/var/run/host/usr/bin` I can see `rpmdev-newspec` binary, but the issue remains the same as in my original report.

**Comment by vrubezhny** [comment]
The fix is provided in linuxtools: https://git.eclipse.org/r/plugins/gitiles/linuxtools/org.eclipse.linuxtools/+/a394f2f2a8bbfb3d71efce14422df2eef1b90cd0

**Comment by akurtakov** [comment]
Using linuxtools master should work.
