### ISSUE TITLE
TM Terminal inside flatpak is in the sandbox (miss configuration, path and so on)

### ISSUE THREAD

**Issue by mickaelistria** [flathub/org.eclipse.Java#4]
From Flatpak Eclipse sandbox, install TM Terminal and then open it.
The terminal user get is from the sandbox, all user's settings and PATH and host applications are ignored, making the terminal almost useless.

**Comment by mbooth101** [comment]
Hmm terminals are a particularly troublesome beast and terminal emulator programs in general are not packaged in Flathub because of this.

(Opinion Alert: TBH I never really thought a terminal integrated into the IDE was a great idea, it's never going to be as full-featured as my dedicated terminal emulator program.)

I will take a look at how it's implemented, if it's some external process it may be trivial to launch to terminal on the host instead.

**Comment by bilelmoussaoui** [comment]
@mbooth101 you might want to look at https://blogs.gnome.org/chergert/2019/04/25/flatpaking-terminals/

**Comment by akurtakov** [comment]
Mat, IMHO it should be OK to make terminal plugin know when run in flatpak to launch e.g. bash from host.

**Comment by mbooth101** [comment]
> @mbooth101 you might want to look at https://blogs.gnome.org/chergert/2019/04/25/flatpaking-terminals/

Thanks for the hint :-)

**Comment by akurtakov** [comment]
The fix landed in CDT and terminal works correct in latest version.
